spring.application.name=anyteam_v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.indent-output=true

# choose use_postgres for the default profile
spring.profiles.active=use_postgres
