# Running both the jar and postgres in same container
spring.datasource.url=jdbc:postgresql://postgres:5432/anyteam_v1_db

# Running the jar and postgres in separate environments
#spring.datasource.url=jdbc:postgresql://localhost:5432/anyteam_v1_db

spring.datasource.username=anyteam_v1_postgres
spring.datasource.password=anyteam_v1_postgres_1234
